asdasd
Num data pts      = 1048576
dt per bin (s)    =                      0.04
Pulse shape       = Spike
Rounding format   = Fractional
Pulse freq (hz)   =                   33.3333
fdot (s-2)        =                         0
fdotdot (s-3)     =                         0
Pulse amp         =                         1
Pulse phs (deg)   =                         0
DC backgrnd level =                         0
Binary period (s) =                         0
Bin asini/c (s)   =                         0
Bin eccentricity  =                         0
Ang of Peri (deg) =                         0
Tm since peri (s) =                         0
Amp Mod amplitude =                         0
Amp Mod phs (deg) =                         0
Amp Mod freq (hz) =                         0
Noise type        = Other
Noise sigma       =                         0
On/Off Pair  1    = 0 1
