
Num data pts      = 32768
dt per bin (s)    =         0.000030517578125
Pulse shape       = Sine
Rounding format   = Fractional
Pulse freq (hz)   =                   10000.5
fdot (s-2)        =                       0.6
fdotdot (s-3)     =                         0
Pulse amp         =                       1.0
Pulse phs (deg)   =                         0
DC backgrnd level =                         0
Binary period (s) =                         0
Bin asini/c (s)   =                         0
Bin eccentricity  =                         0
Ang of Peri (deg) =                         0
Tm since peri (s) =                         0
Amp Mod amplitude =                         0
Amp Mod phs (deg) =                         0
Amp Mod freq (hz) =                         0
Noise type        = Other
Noise sigma       =                       0.0
On/Off Pair  1    = 0 1
