#ifndef __readfile_cmd__
#define __readfile_cmd__
/*****
  command line parser interface -- generated by clig 
  (http://wsd.iitb.fhg.de/~kir/clighome/)

  The command line parser `clig':
  (C) 1995,1997,1998,1999,2000 Harald Kirsch (kir@iitb.fhg.de)
*****/

typedef struct s_Cmdline {
  /***** -nopage: Don't paginate the output like 'more' */
  char nopageP;
  /***** -byte: Raw data in byte format */
  char bytP;
  /***** -b: Raw data in byte format */
  char sbytP;
  /***** -float: Raw data in floating point format */
  char fltP;
  /***** -f: Raw data in floating point format */
  char sfltP;
  /***** -double: Raw data in double precision format */
  char dblP;
  /***** -d: Raw data in double precision format */
  char sdblP;
  /***** -fcomplex: Raw data in float-complex format */
  char fcxP;
  /***** -fc: Raw data in float-complex format */
  char sfcxP;
  /***** -dcomplex: Raw data in double-complex format */
  char dcxP;
  /***** -dc: Raw data in double-complex format */
  char sdcxP;
  /***** -int: Raw data in integer format */
  char igrP;
  /***** -i: Raw data in integer format */
  char sigrP;
  /***** -long: Raw data in long format */
  char lngP;
  /***** -l: Raw data in long format */
  char slngP;
  /***** -rzwcand: Raw data in rzw search candidate format */
  char rzwP;
  /***** -rzw: Raw data in rzw search candidate format */
  char srzwP;
  /***** -bincand: Raw data in bin search candidate format */
  char binP;
  /***** -bin: Raw data in bin search candidate format */
  char sbinP;
  /***** -position: Raw data in position struct format */
  char posP;
  /***** -pos: Raw data in position struct format */
  char sposP;
  /***** -pkmb: Raw data in Parkes Multibeam format */
  char pksP;
  /***** -pk: Raw data in Parkes Multibeam format */
  char spksP;
  /***** -bpp: Raw data in BPP format */
  char bppP;
  /***** -wapp: Raw data in WAPP format */
  char wappP;
  /***** -fortran: Raw data was written by a fortran program */
  char fortranP;
  /***** -index: The range of objects to display */
  char indexP;
  int *index;
  int indexC;
  /***** -nph: 0th FFT bin amplitude (for 'RZW' data) */
  char nphP;
  double nph;
  int nphC;
  /***** uninterpreted command line parameters */
  int argc;
  /*@null*/char **argv;
  /***** the whole command line concatenated */
  char *full_cmd_line;
} Cmdline;


extern char *Program;
extern void usage(void);
extern /*@shared*/Cmdline *parseCmdline(int argc, char **argv);

extern void showOptionValues(void);

#endif

