#ifndef __rfifind_cmd__
#define __rfifind_cmd__
/*****
  command line parser interface -- generated by clig 
  (http://wsd.iitb.fhg.de/~kir/clighome/)

  The command line parser `clig':
  (C) 1995,1997,1998,1999,2000 Harald Kirsch (kir@iitb.fhg.de)
*****/

typedef struct s_Cmdline {
  /***** -o: Output data file name (no suffix) */
  char outfileP;
  char* outfile;
  int outfileC;
  /***** -pkmb: Raw data in Parkes Multibeam format */
  char pkmbP;
  /***** -ebpp: Raw data in Efflesberg-Berkeley Pulsar Processor format */
  char ebppP;
  /***** -gbpp: Raw data in Green Bank-Berkeley Pulsar Processor format */
  char gbppP;
  /***** -nofft: Will not attempt to calculate the FFT of the zero-DM data */
  char nofftP;
  /***** -time: The number of minutes to integrate for statistics and FFT calculations */
  char timeP;
  float time;
  int timeC;
  /***** -sigma: The sigma above/below the noise to reject a chunk of data */
  char sigmaP;
  float sigma;
  int sigmaC;
  /***** -zapchan: Channels to explicitly remove from analysis */
  char zapchanP;
  int *zapchan;
  int zapchanC;
  /***** uninterpreted command line parameters */
  int argc;
  /*@null*/char **argv;
  /***** the whole command line concatenated */
  char *full_cmd_line;
} Cmdline;


extern char *Program;
extern void usage(void);
extern /*@shared*/Cmdline *parseCmdline(int argc, char **argv);

extern void showOptionValues(void);

#endif

