#ifndef __search_bin_cmd__
#define __search_bin_cmd__
/*****
  command line parser interface 
                        -- generated by clig (Version: 1.0.1)

  The command line parser `clig':
  (C) 1995 Harald Kirsch (kir@iitb.fhg.de)
*****/

#ifndef FALSE
#  define FALSE (1==0)
#  define TRUE  (!FALSE)
#endif

typedef struct s_Cmdline {
  /***** -ncand: Number of candidates to try to return */
  char ncandP;
  int ncand;
  int ncandC;
  /***** -plev: Closely examine candidates above this power level */
  char plevP;
  double plev;
  int plevC;
  /***** -minfft: Power-of-2 length of the shortest miniFFT */
  char minfftP;
  int minfft;
  int minfftC;
  /***** -maxfft: Power-of-2 length of the longest miniFFT */
  char maxfftP;
  int maxfft;
  int maxfftC;
  /***** -rlo: The low Fourier frequency to check */
  char rloP;
  int rlo;
  int rloC;
  /***** -rhi: The high Fourier frequency to check */
  char rhiP;
  int rhi;
  int rhiC;
  /***** -lobin: The first Fourier frequency in the data file */
  char lobinP;
  int lobin;
  int lobinC;
  /***** -sum: Number of stacked power spectra making up the data.  (The default means the data are complex amplitudes) */
  char sumP;
  int sum;
  int sumC;
  /***** uninterpreted command line parameters */
  int argc;
  /*@null*/char **argv;
  /***** the whole command line concatenated */
  char *full_cmd_line;
} Cmdline;


extern char *Program;
extern void usage(void);
extern /*@shared*/Cmdline *parseCmdline(int argc, char **argv);

extern void showOptionValues(void);

#endif

