/*****
  command line parser -- generated by clig
  (http://wsd.iitb.fhg.de/~kir/clighome/)

  The command line parser `clig':
  (C) 1995,1996,1997,1998,1999,2000 Harald Kirsch (kir@iitb.fhg.de)
*****/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <errno.h>
#include <limits.h>
#include <float.h>
#include <math.h>

#include "prepfold_cmd.h"

char *Program;

/*@-null*/

static Cmdline cmd = {
  /***** -pkmb: Raw data in Parkes Multibeam format */
  /* pkmbP = */ 0,
  /***** -ebpp: Raw data in Effelsberg-Berkeley Pulsar Processor format.  CURRENTLY UNSUPPORTED */
  /* ebppP = */ 0,
  /***** -nobary: Do not barycenter (assume input parameters are topocentric) */
  /* nobaryP = */ 0,
  /***** -DE405: Use the DE405 ephemeris for barycentering instead of DE200 (the default) */
  /* de405P = */ 0,
  /***** -xwin: Show the result plots on-screen as well as make a plotfile */
  /* xwinP = */ 0,
  /***** -dm: The central DM of the search (cm^-3 pc) */
  /* dmP = */ 1,
  /* dm = */ 0,
  /* dmC = */ 1,
  /***** -n: The number of bins in the profile.  Defaults to the number of sampling bins which correspond to one folded period */
  /* proflenP = */ 0,
  /* proflen = */ (int)0,
  /* proflenC = */ 0,
  /***** -nsub: The number of sub-bands to use for the DM search */
  /* nsubP = */ 1,
  /* nsub = */ 32,
  /* nsubC = */ 1,
  /***** -npart: The number of sub-integrations to use for the period search */
  /* npartP = */ 1,
  /* npart = */ 64,
  /* npartC = */ 1,
  /***** -pstep: The minimum period stepsize over the observation in profile bins */
  /* pstepP = */ 1,
  /* pstep = */ 2,
  /* pstepC = */ 1,
  /***** -pdstep: The minimum P-dot stepsize over the observation in profile bins */
  /* pdstepP = */ 1,
  /* pdstep = */ 4,
  /* pdstepC = */ 1,
  /***** -dmstep: The minimum DM stepsize over the observation in profile bins */
  /* dmstepP = */ 1,
  /* dmstep = */ 2,
  /* dmstepC = */ 1,
  /***** -npfact: 2 * npfact * proflen + 1 periods and p-dots will be searched */
  /* npfactP = */ 1,
  /* npfact = */ 2,
  /* npfactC = */ 1,
  /***** -ndmfact: 2 * ndmfact * proflen + 1 DMs will be searched */
  /* ndmfactP = */ 1,
  /* ndmfact = */ 3,
  /* ndmfactC = */ 1,
  /***** -p: The nominative folding period (s) */
  /* pP = */ 0,
  /* p = */ (double)0,
  /* pC = */ 0,
  /***** -pd: The nominative period derivative (s/s) */
  /* pdP = */ 1,
  /* pd = */ 0.0,
  /* pdC = */ 1,
  /***** -pdd: The nominative period 2nd derivative (s/s^2) */
  /* pddP = */ 1,
  /* pdd = */ 0.0,
  /* pddC = */ 1,
  /***** -f: The nominative folding frequency (hz) */
  /* fP = */ 0,
  /* f = */ (double)0,
  /* fC = */ 0,
  /***** -fd: The nominative frequency derivative (hz/s) */
  /* fdP = */ 1,
  /* fd = */ 0,
  /* fdC = */ 1,
  /***** -fdd: The nominative frequency 2nd derivative (hz/s^2) */
  /* fddP = */ 1,
  /* fdd = */ 0,
  /* fddC = */ 1,
  /***** -phs: Offset phase for the profil */
  /* phsP = */ 1,
  /* phs = */ 0.0,
  /* phsC = */ 1,
  /***** -start: The folding start time as a fraction of the full obs */
  /* startTP = */ 1,
  /* startT = */ 0.0,
  /* startTC = */ 1,
  /***** -end: The folding end time as a fraction of the full obs */
  /* endTP = */ 1,
  /* endT = */ 1.0,
  /* endTC = */ 1,
  /***** -psr: Name of pulsar to fold (do not include J or B) */
  /* psrnameP = */ 0,
  /* psrname = */ (char*)0,
  /* psrnameC = */ 0,
  /***** -obs: Two letter TEMPO observatory code (for barycentering) */
  /* obscodeP = */ 0,
  /* obscode = */ (char*)0,
  /* obscodeC = */ 0,
  /***** -rzwcand: The candidate number to fold from 'infile'_rzw.cand */
  /* rzwcandP = */ 0,
  /* rzwcand = */ (int)0,
  /* rzwcandC = */ 0,
  /***** -rzwfile: Name of the rzw search file to use (include the full name of the file) */
  /* rzwfileP = */ 0,
  /* rzwfile = */ (char*)0,
  /* rzwfileC = */ 0,
  /***** -bin: Fold a binary pulsar.  Must include all of the following parameters */
  /* binaryP = */ 0,
  /***** -pb: The orbital period (s) */
  /* pbP = */ 0,
  /* pb = */ (double)0,
  /* pbC = */ 0,
  /***** -x: The projected orbital semi-major axis (lt-sec) */
  /* asinicP = */ 0,
  /* asinic = */ (double)0,
  /* asinicC = */ 0,
  /***** -e: The orbital eccentricity */
  /* eP = */ 1,
  /* e = */ 0,
  /* eC = */ 1,
  /***** -To: The time of periastron passage (MJD) */
  /* ToP = */ 0,
  /* To = */ (double)0,
  /* ToC = */ 0,
  /***** -w: Longitude of periastron (deg) */
  /* wP = */ 0,
  /* w = */ (double)0,
  /* wC = */ 0,
  /***** -wdot: Rate of advance of periastron (deg/yr) */
  /* wdotP = */ 1,
  /* wdot = */ 0,
  /* wdotC = */ 1,
  /***** uninterpreted rest of command line */
  /* argc = */ 0,
  /* argv = */ (char**)0,
  /***** the original command line concatenated */
  /* full_cmd_line = */ NULL
};

/*@=null*/

/***** let LCLint run more smoothly */
/*@-predboolothers*/
/*@-boolops*/


/******************************************************************/
/*****
 This is a bit tricky. We want to make a difference between overflow
 and underflow and we want to allow v==Inf or v==-Inf but not
 v>FLT_MAX. 

 We don't use fabs to avoid linkage with -lm.
*****/
static void
checkFloatConversion(double v, char *option, char *arg)
{
  char *err = NULL;

  if( (errno==ERANGE && v!=0.0) /* even double overflowed */
      || (v<HUGE_VAL && v>-HUGE_VAL && (v<0.0?-v:v)>(double)FLT_MAX) ) {
    err = "large";
  } else if( (errno==ERANGE && v==0.0) 
	     || (v!=0.0 && (v<0.0?-v:v)<(double)FLT_MIN) ) {
    err = "small";
  }
  if( err ) {
    fprintf(stderr, 
	    "%s: parameter `%s' of option `%s' to %s to represent\n",
	    Program, arg, option, err);
    exit(EXIT_FAILURE);
  }
}

int
getIntOpt(int argc, char **argv, int i, int *value, int force)
{
  char *end;
  long v;

  if( ++i>=argc ) goto nothingFound;

  errno = 0;
  v = strtol(argv[i], &end, 0);

  /***** check for conversion error */
  if( end==argv[i] ) goto nothingFound;

  /***** check for surplus non-whitespace */
  while( isspace(*end) ) end+=1;
  if( *end ) goto nothingFound;

  /***** check if it fits into an int */
  if( errno==ERANGE || v>(long)INT_MAX || v<(long)INT_MIN ) {
    fprintf(stderr, 
	    "%s: parameter `%s' of option `%s' to large to represent\n",
	    Program, argv[i], argv[i-1]);
    exit(EXIT_FAILURE);
  }
  *value = (int)v;

  return i;

nothingFound:
  if( !force ) return i-1;

  fprintf(stderr, 
	  "%s: missing or malformed integer value after option `%s'\n",
	  Program, argv[i-1]);
    exit(EXIT_FAILURE);
}
/**********************************************************************/

int
getIntOpts(int argc, char **argv, int i, 
	   int **values,
	   int cmin, int cmax)
/*****
  We want to find at least cmin values and at most cmax values.
  cmax==-1 then means infinitely many are allowed.
*****/
{
  int alloced, used;
  char *end;
  long v;
  if( i+cmin >= argc ) {
    fprintf(stderr, 
	    "%s: option `%s' wants at least %d parameters\n",
	    Program, argv[i], cmin);
    exit(EXIT_FAILURE);
  }

  /***** 
    alloc a bit more than cmin values. It does not hurt to have room
    for a bit more values than cmax.
  *****/
  alloced = cmin + 4;
  *values = (int*)calloc((size_t)alloced, sizeof(int));
  if( ! *values ) {
outMem:
    fprintf(stderr, 
	    "%s: out of memory while parsing option `%s'\n",
	    Program, argv[i]);
    exit(EXIT_FAILURE);
  }

  for(used=0; (cmax==-1 || used<cmax) && used+i+1<argc; used++) {
    if( used==alloced ) {
      alloced += 8;
      *values = (int *) realloc(*values, alloced*sizeof(int));
      if( !*values ) goto outMem;
    }

    errno = 0;
    v = strtol(argv[used+i+1], &end, 0);

    /***** check for conversion error */
    if( end==argv[used+i+1] ) break;

    /***** check for surplus non-whitespace */
    while( isspace(*end) ) end+=1;
    if( *end ) break;

    /***** check for overflow */
    if( errno==ERANGE || v>(long)INT_MAX || v<(long)INT_MIN ) {
      fprintf(stderr, 
	      "%s: parameter `%s' of option `%s' to large to represent\n",
	      Program, argv[i+used+1], argv[i]);
      exit(EXIT_FAILURE);
    }

    (*values)[used] = (int)v;

  }
    
  if( used<cmin ) {
    fprintf(stderr, 
	    "%s: parameter `%s' of `%s' should be an "
	    "integer value\n",
	    Program, argv[i+used+1], argv[i]);
    exit(EXIT_FAILURE);
  }

  return i+used;
}
/**********************************************************************/

int
getLongOpt(int argc, char **argv, int i, long *value, int force)
{
  char *end;

  if( ++i>=argc ) goto nothingFound;

  errno = 0;
  *value = strtol(argv[i], &end, 0);

  /***** check for conversion error */
  if( end==argv[i] ) goto nothingFound;

  /***** check for surplus non-whitespace */
  while( isspace(*end) ) end+=1;
  if( *end ) goto nothingFound;

  /***** check for overflow */
  if( errno==ERANGE ) {
    fprintf(stderr, 
	    "%s: parameter `%s' of option `%s' to large to represent\n",
	    Program, argv[i], argv[i-1]);
    exit(EXIT_FAILURE);
  }
  return i;

nothingFound:
  /***** !force means: this parameter may be missing.*/
  if( !force ) return i-1;

  fprintf(stderr, 
	  "%s: missing or malformed value after option `%s'\n",
	  Program, argv[i-1]);
    exit(EXIT_FAILURE);
}
/**********************************************************************/

int
getLongOpts(int argc, char **argv, int i, 
	    long **values,
	    int cmin, int cmax)
/*****
  We want to find at least cmin values and at most cmax values.
  cmax==-1 then means infinitely many are allowed.
*****/
{
  int alloced, used;
  char *end;

  if( i+cmin >= argc ) {
    fprintf(stderr, 
	    "%s: option `%s' wants at least %d parameters\n",
	    Program, argv[i], cmin);
    exit(EXIT_FAILURE);
  }

  /***** 
    alloc a bit more than cmin values. It does not hurt to have room
    for a bit more values than cmax.
  *****/
  alloced = cmin + 4;
  *values = calloc((size_t)alloced, sizeof(long));
  if( ! *values ) {
outMem:
    fprintf(stderr, 
	    "%s: out of memory while parsing option `%s'\n",
	    Program, argv[i]);
    exit(EXIT_FAILURE);
  }

  for(used=0; (cmax==-1 || used<cmax) && used+i+1<argc; used++) {
    if( used==alloced ) {
      alloced += 8;
      *values = realloc(*values, alloced*sizeof(long));
      if( !*values ) goto outMem;
    }

    errno = 0;
    (*values)[used] = strtol(argv[used+i+1], &end, 0);

    /***** check for conversion error */
    if( end==argv[used+i+1] ) break;

    /***** check for surplus non-whitespace */
    while( isspace(*end) ) end+=1; 
    if( *end ) break;

    /***** check for overflow */
    if( errno==ERANGE ) {
      fprintf(stderr, 
	      "%s: parameter `%s' of option `%s' to large to represent\n",
	      Program, argv[i+used+1], argv[i]);
      exit(EXIT_FAILURE);
    }

  }
    
  if( used<cmin ) {
    fprintf(stderr, 
	    "%s: parameter `%s' of `%s' should be an "
	    "integer value\n",
	    Program, argv[i+used+1], argv[i]);
    exit(EXIT_FAILURE);
  }

  return i+used;
}
/**********************************************************************/

int
getFloatOpt(int argc, char **argv, int i, float *value, int force)
{
  char *end;
  double v;

  if( ++i>=argc ) goto nothingFound;

  errno = 0;
  v = strtod(argv[i], &end);

  /***** check for conversion error */
  if( end==argv[i] ) goto nothingFound;

  /***** check for surplus non-whitespace */
  while( isspace(*end) ) end+=1;
  if( *end ) goto nothingFound;

  /***** check for overflow */
  checkFloatConversion(v, argv[i-1], argv[i]);

  *value = (float)v;

  return i;

nothingFound:
  if( !force ) return i-1;

  fprintf(stderr,
	  "%s: missing or malformed float value after option `%s'\n",
	  Program, argv[i-1]);
  exit(EXIT_FAILURE);
 
}
/**********************************************************************/

int
getFloatOpts(int argc, char **argv, int i, 
	   float **values,
	   int cmin, int cmax)
/*****
  We want to find at least cmin values and at most cmax values.
  cmax==-1 then means infinitely many are allowed.
*****/
{
  int alloced, used;
  char *end;
  double v;

  if( i+cmin >= argc ) {
    fprintf(stderr, 
	    "%s: option `%s' wants at least %d parameters\n",
	    Program, argv[i], cmin);
    exit(EXIT_FAILURE);
  }

  /***** 
    alloc a bit more than cmin values.
  *****/
  alloced = cmin + 4;
  *values = (float*)calloc((size_t)alloced, sizeof(float));
  if( ! *values ) {
outMem:
    fprintf(stderr, 
	    "%s: out of memory while parsing option `%s'\n",
	    Program, argv[i]);
    exit(EXIT_FAILURE);
  }

  for(used=0; (cmax==-1 || used<cmax) && used+i+1<argc; used++) {
    if( used==alloced ) {
      alloced += 8;
      *values = (float *) realloc(*values, alloced*sizeof(float));
      if( !*values ) goto outMem;
    }

    errno = 0;
    v = strtod(argv[used+i+1], &end);

    /***** check for conversion error */
    if( end==argv[used+i+1] ) break;

    /***** check for surplus non-whitespace */
    while( isspace(*end) ) end+=1;
    if( *end ) break;

    /***** check for overflow */
    checkFloatConversion(v, argv[i], argv[i+used+1]);
    
    (*values)[used] = (float)v;
  }
    
  if( used<cmin ) {
    fprintf(stderr, 
	    "%s: parameter `%s' of `%s' should be a "
	    "floating-point value\n",
	    Program, argv[i+used+1], argv[i]);
    exit(EXIT_FAILURE);
  }

  return i+used;
}
/**********************************************************************/

int
getDoubleOpt(int argc, char **argv, int i, double *value, int force)
{
  char *end;

  if( ++i>=argc ) goto nothingFound;

  errno = 0;
  *value = strtod(argv[i], &end);

  /***** check for conversion error */
  if( end==argv[i] ) goto nothingFound;

  /***** check for surplus non-whitespace */
  while( isspace(*end) ) end+=1;
  if( *end ) goto nothingFound;

  /***** check for overflow */
  if( errno==ERANGE ) {
    fprintf(stderr, 
	    "%s: parameter `%s' of option `%s' to %s to represent\n",
	    Program, argv[i], argv[i-1],
	    (*value==0.0 ? "small" : "large"));
    exit(EXIT_FAILURE);
  }

  return i;

nothingFound:
  if( !force ) return i-1;

  fprintf(stderr,
	  "%s: missing or malformed value after option `%s'\n",
	  Program, argv[i-1]);
  exit(EXIT_FAILURE);
 
}
/**********************************************************************/

int
getDoubleOpts(int argc, char **argv, int i, 
	   double **values,
	   int cmin, int cmax)
/*****
  We want to find at least cmin values and at most cmax values.
  cmax==-1 then means infinitely many are allowed.
*****/
{
  int alloced, used;
  char *end;

  if( i+cmin >= argc ) {
    fprintf(stderr, 
	    "%s: option `%s' wants at least %d parameters\n",
	    Program, argv[i], cmin);
    exit(EXIT_FAILURE);
  }

  /***** 
    alloc a bit more than cmin values.
  *****/
  alloced = cmin + 4;
  *values = (double*)calloc((size_t)alloced, sizeof(double));
  if( ! *values ) {
outMem:
    fprintf(stderr, 
	    "%s: out of memory while parsing option `%s'\n",
	    Program, argv[i]);
    exit(EXIT_FAILURE);
  }

  for(used=0; (cmax==-1 || used<cmax) && used+i+1<argc; used++) {
    if( used==alloced ) {
      alloced += 8;
      *values = (double *) realloc(*values, alloced*sizeof(double));
      if( !*values ) goto outMem;
    }

    errno = 0;
    (*values)[used] = strtod(argv[used+i+1], &end);

    /***** check for conversion error */
    if( end==argv[used+i+1] ) break;

    /***** check for surplus non-whitespace */
    while( isspace(*end) ) end+=1;
    if( *end ) break;

    /***** check for overflow */
    if( errno==ERANGE ) {
      fprintf(stderr, 
	      "%s: parameter `%s' of option `%s' to %s to represent\n",
	      Program, argv[i+used+1], argv[i],
	      ((*values)[used]==0.0 ? "small" : "large"));
      exit(EXIT_FAILURE);
    }

  }
    
  if( used<cmin ) {
    fprintf(stderr, 
	    "%s: parameter `%s' of `%s' should be a "
	    "double value\n",
	    Program, argv[i+used+1], argv[i]);
    exit(EXIT_FAILURE);
  }

  return i+used;
}
/**********************************************************************/

int
getStringOpt(int argc, char **argv, int i, char **value, int force)
{
  if( ++i>=argc ) {
    fprintf(stderr, "%s: missing string after option `%s'\n",
            Program, argv[i-1]);
    exit(EXIT_FAILURE);
  }
  
  if( !force && argv[i+1][0] == '-' ) return i-1;
  *value = argv[i];
  return i;
}
/**********************************************************************/

int
getStringOpts(int argc, char **argv, int i, 
	   char*  **values,
	   int cmin, int cmax)
/*****
  We want to find at least cmin values and at most cmax values.
  cmax==-1 then means infinitely many are allowed.
*****/
{
  int alloced, used;

  if( i+cmin >= argc ) {
    fprintf(stderr, 
	    "%s: option `%s' wants at least %d parameters\n",
	    Program, argv[i], cmin);
    exit(EXIT_FAILURE);
  }

  alloced = cmin + 4;
    
  *values = (char**)calloc((size_t)alloced, sizeof(char*));
  if( ! *values ) {
outMem:
    fprintf(stderr, 
	    "%s: out of memory during parsing of option `%s'\n",
	    Program, argv[i]);
    exit(EXIT_FAILURE);
  }

  for(used=0; (cmax==-1 || used<cmax) && used+i+1<argc; used++) {
    if( used==alloced ) {
      alloced += 8;
      *values = (char **)realloc(*values, alloced*sizeof(char*));
      if( !*values ) goto outMem;
    }

    if( used>=cmin && argv[used+i+1][0]=='-' ) break;
    (*values)[used] = argv[used+i+1];
  }
    
  if( used<cmin ) {
    fprintf(stderr, 
    "%s: less than %d parameters for option `%s', only %d found\n",
	    Program, cmin, argv[i], used);
    exit(EXIT_FAILURE);
  }

  return i+used;
}
/**********************************************************************/

void
checkIntLower(char *opt, int *values, int count, int max)
{
  int i;

  for(i=0; i<count; i++) {
    if( values[i]<=max ) continue;
    fprintf(stderr, 
	    "%s: parameter %d of option `%s' greater than max=%d\n",
	    Program, i+1, opt, max);
    exit(EXIT_FAILURE);
  }
}
/**********************************************************************/

void
checkIntHigher(char *opt, int *values, int count, int min)
{
  int i;

  for(i=0; i<count; i++) {
    if( values[i]>=min ) continue;
    fprintf(stderr, 
	    "%s: parameter %d of option `%s' smaller than min=%d\n",
	    Program, i+1, opt, min);
    exit(EXIT_FAILURE);
  }
}
/**********************************************************************/

void
checkLongLower(char *opt, long *values, int count, long max)
{
  int i;

  for(i=0; i<count; i++) {
    if( values[i]<=max ) continue;
    fprintf(stderr, 
	    "%s: parameter %d of option `%s' greater than max=%ld\n",
	    Program, i+1, opt, max);
    exit(EXIT_FAILURE);
  }
}
/**********************************************************************/

void
checkLongHigher(char *opt, long *values, int count, long min)
{
  int i;

  for(i=0; i<count; i++) {
    if( values[i]>=min ) continue;
    fprintf(stderr, 
	    "%s: parameter %d of option `%s' smaller than min=%ld\n",
	    Program, i+1, opt, min);
    exit(EXIT_FAILURE);
  }
}
/**********************************************************************/

void
checkFloatLower(char *opt, float *values, int count, float max)
{
  int i;

  for(i=0; i<count; i++) {
    if( values[i]<=max ) continue;
    fprintf(stderr, 
	    "%s: parameter %d of option `%s' greater than max=%f\n",
	    Program, i+1, opt, max);
    exit(EXIT_FAILURE);
  }
}
/**********************************************************************/

void
checkFloatHigher(char *opt, float *values, int count, float min)
{
  int i;

  for(i=0; i<count; i++) {
    if( values[i]>=min ) continue;
    fprintf(stderr, 
	    "%s: parameter %d of option `%s' smaller than min=%f\n",
	    Program, i+1, opt, min);
    exit(EXIT_FAILURE);
  }
}
/**********************************************************************/

void
checkDoubleLower(char *opt, double *values, int count, double max)
{
  int i;

  for(i=0; i<count; i++) {
    if( values[i]<=max ) continue;
    fprintf(stderr, 
	    "%s: parameter %d of option `%s' greater than max=%f\n",
	    Program, i+1, opt, max);
    exit(EXIT_FAILURE);
  }
}
/**********************************************************************/

void
checkDoubleHigher(char *opt, double *values, int count, double min)
{
  int i;

  for(i=0; i<count; i++) {
    if( values[i]>=min ) continue;
    fprintf(stderr, 
	    "%s: parameter %d of option `%s' smaller than min=%f\n",
	    Program, i+1, opt, min);
    exit(EXIT_FAILURE);
  }
}
/**********************************************************************/

static char *
catArgv(int argc, char **argv)
{
  int i;
  size_t l;
  char *s, *t;

  for(i=0, l=0; i<argc; i++) l += (1+strlen(argv[i]));
  s = (char *)malloc(l);
  if( !s ) {
    fprintf(stderr, "%s: out of memory\n", Program);
    exit(EXIT_FAILURE);
  }
  strcpy(s, argv[0]);
  t = s;
  for(i=1; i<argc; i++) {
    t = t+strlen(t);
    *t++ = ' ';
    strcpy(t, argv[i]);
  }
  return s;
}
/**********************************************************************/

void
showOptionValues(void)
{
  int i;

  printf("Full command line is:\n`%s'\n", cmd.full_cmd_line);

  /***** -pkmb: Raw data in Parkes Multibeam format */
  if( !cmd.pkmbP ) {
    printf("-pkmb not found.\n");
  } else {
    printf("-pkmb found:\n");
  }

  /***** -ebpp: Raw data in Effelsberg-Berkeley Pulsar Processor format.  CURRENTLY UNSUPPORTED */
  if( !cmd.ebppP ) {
    printf("-ebpp not found.\n");
  } else {
    printf("-ebpp found:\n");
  }

  /***** -nobary: Do not barycenter (assume input parameters are topocentric) */
  if( !cmd.nobaryP ) {
    printf("-nobary not found.\n");
  } else {
    printf("-nobary found:\n");
  }

  /***** -DE405: Use the DE405 ephemeris for barycentering instead of DE200 (the default) */
  if( !cmd.de405P ) {
    printf("-DE405 not found.\n");
  } else {
    printf("-DE405 found:\n");
  }

  /***** -xwin: Show the result plots on-screen as well as make a plotfile */
  if( !cmd.xwinP ) {
    printf("-xwin not found.\n");
  } else {
    printf("-xwin found:\n");
  }

  /***** -dm: The central DM of the search (cm^-3 pc) */
  if( !cmd.dmP ) {
    printf("-dm not found.\n");
  } else {
    printf("-dm found:\n");
    if( !cmd.dmC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%.40g'\n", cmd.dm);
    }
  }

  /***** -n: The number of bins in the profile.  Defaults to the number of sampling bins which correspond to one folded period */
  if( !cmd.proflenP ) {
    printf("-n not found.\n");
  } else {
    printf("-n found:\n");
    if( !cmd.proflenC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%d'\n", cmd.proflen);
    }
  }

  /***** -nsub: The number of sub-bands to use for the DM search */
  if( !cmd.nsubP ) {
    printf("-nsub not found.\n");
  } else {
    printf("-nsub found:\n");
    if( !cmd.nsubC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%d'\n", cmd.nsub);
    }
  }

  /***** -npart: The number of sub-integrations to use for the period search */
  if( !cmd.npartP ) {
    printf("-npart not found.\n");
  } else {
    printf("-npart found:\n");
    if( !cmd.npartC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%d'\n", cmd.npart);
    }
  }

  /***** -pstep: The minimum period stepsize over the observation in profile bins */
  if( !cmd.pstepP ) {
    printf("-pstep not found.\n");
  } else {
    printf("-pstep found:\n");
    if( !cmd.pstepC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%d'\n", cmd.pstep);
    }
  }

  /***** -pdstep: The minimum P-dot stepsize over the observation in profile bins */
  if( !cmd.pdstepP ) {
    printf("-pdstep not found.\n");
  } else {
    printf("-pdstep found:\n");
    if( !cmd.pdstepC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%d'\n", cmd.pdstep);
    }
  }

  /***** -dmstep: The minimum DM stepsize over the observation in profile bins */
  if( !cmd.dmstepP ) {
    printf("-dmstep not found.\n");
  } else {
    printf("-dmstep found:\n");
    if( !cmd.dmstepC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%d'\n", cmd.dmstep);
    }
  }

  /***** -npfact: 2 * npfact * proflen + 1 periods and p-dots will be searched */
  if( !cmd.npfactP ) {
    printf("-npfact not found.\n");
  } else {
    printf("-npfact found:\n");
    if( !cmd.npfactC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%d'\n", cmd.npfact);
    }
  }

  /***** -ndmfact: 2 * ndmfact * proflen + 1 DMs will be searched */
  if( !cmd.ndmfactP ) {
    printf("-ndmfact not found.\n");
  } else {
    printf("-ndmfact found:\n");
    if( !cmd.ndmfactC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%d'\n", cmd.ndmfact);
    }
  }

  /***** -p: The nominative folding period (s) */
  if( !cmd.pP ) {
    printf("-p not found.\n");
  } else {
    printf("-p found:\n");
    if( !cmd.pC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%.40g'\n", cmd.p);
    }
  }

  /***** -pd: The nominative period derivative (s/s) */
  if( !cmd.pdP ) {
    printf("-pd not found.\n");
  } else {
    printf("-pd found:\n");
    if( !cmd.pdC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%.40g'\n", cmd.pd);
    }
  }

  /***** -pdd: The nominative period 2nd derivative (s/s^2) */
  if( !cmd.pddP ) {
    printf("-pdd not found.\n");
  } else {
    printf("-pdd found:\n");
    if( !cmd.pddC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%.40g'\n", cmd.pdd);
    }
  }

  /***** -f: The nominative folding frequency (hz) */
  if( !cmd.fP ) {
    printf("-f not found.\n");
  } else {
    printf("-f found:\n");
    if( !cmd.fC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%.40g'\n", cmd.f);
    }
  }

  /***** -fd: The nominative frequency derivative (hz/s) */
  if( !cmd.fdP ) {
    printf("-fd not found.\n");
  } else {
    printf("-fd found:\n");
    if( !cmd.fdC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%.40g'\n", cmd.fd);
    }
  }

  /***** -fdd: The nominative frequency 2nd derivative (hz/s^2) */
  if( !cmd.fddP ) {
    printf("-fdd not found.\n");
  } else {
    printf("-fdd found:\n");
    if( !cmd.fddC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%.40g'\n", cmd.fdd);
    }
  }

  /***** -phs: Offset phase for the profil */
  if( !cmd.phsP ) {
    printf("-phs not found.\n");
  } else {
    printf("-phs found:\n");
    if( !cmd.phsC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%.40g'\n", cmd.phs);
    }
  }

  /***** -start: The folding start time as a fraction of the full obs */
  if( !cmd.startTP ) {
    printf("-start not found.\n");
  } else {
    printf("-start found:\n");
    if( !cmd.startTC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%.40g'\n", cmd.startT);
    }
  }

  /***** -end: The folding end time as a fraction of the full obs */
  if( !cmd.endTP ) {
    printf("-end not found.\n");
  } else {
    printf("-end found:\n");
    if( !cmd.endTC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%.40g'\n", cmd.endT);
    }
  }

  /***** -psr: Name of pulsar to fold (do not include J or B) */
  if( !cmd.psrnameP ) {
    printf("-psr not found.\n");
  } else {
    printf("-psr found:\n");
    if( !cmd.psrnameC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%s'\n", cmd.psrname);
    }
  }

  /***** -obs: Two letter TEMPO observatory code (for barycentering) */
  if( !cmd.obscodeP ) {
    printf("-obs not found.\n");
  } else {
    printf("-obs found:\n");
    if( !cmd.obscodeC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%s'\n", cmd.obscode);
    }
  }

  /***** -rzwcand: The candidate number to fold from 'infile'_rzw.cand */
  if( !cmd.rzwcandP ) {
    printf("-rzwcand not found.\n");
  } else {
    printf("-rzwcand found:\n");
    if( !cmd.rzwcandC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%d'\n", cmd.rzwcand);
    }
  }

  /***** -rzwfile: Name of the rzw search file to use (include the full name of the file) */
  if( !cmd.rzwfileP ) {
    printf("-rzwfile not found.\n");
  } else {
    printf("-rzwfile found:\n");
    if( !cmd.rzwfileC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%s'\n", cmd.rzwfile);
    }
  }

  /***** -bin: Fold a binary pulsar.  Must include all of the following parameters */
  if( !cmd.binaryP ) {
    printf("-bin not found.\n");
  } else {
    printf("-bin found:\n");
  }

  /***** -pb: The orbital period (s) */
  if( !cmd.pbP ) {
    printf("-pb not found.\n");
  } else {
    printf("-pb found:\n");
    if( !cmd.pbC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%.40g'\n", cmd.pb);
    }
  }

  /***** -x: The projected orbital semi-major axis (lt-sec) */
  if( !cmd.asinicP ) {
    printf("-x not found.\n");
  } else {
    printf("-x found:\n");
    if( !cmd.asinicC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%.40g'\n", cmd.asinic);
    }
  }

  /***** -e: The orbital eccentricity */
  if( !cmd.eP ) {
    printf("-e not found.\n");
  } else {
    printf("-e found:\n");
    if( !cmd.eC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%.40g'\n", cmd.e);
    }
  }

  /***** -To: The time of periastron passage (MJD) */
  if( !cmd.ToP ) {
    printf("-To not found.\n");
  } else {
    printf("-To found:\n");
    if( !cmd.ToC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%.40g'\n", cmd.To);
    }
  }

  /***** -w: Longitude of periastron (deg) */
  if( !cmd.wP ) {
    printf("-w not found.\n");
  } else {
    printf("-w found:\n");
    if( !cmd.wC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%.40g'\n", cmd.w);
    }
  }

  /***** -wdot: Rate of advance of periastron (deg/yr) */
  if( !cmd.wdotP ) {
    printf("-wdot not found.\n");
  } else {
    printf("-wdot found:\n");
    if( !cmd.wdotC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%.40g'\n", cmd.wdot);
    }
  }
  if( !cmd.argc ) {
    printf("no remaining parameters in argv\n");
  } else {
    printf("argv =");
    for(i=0; i<cmd.argc; i++) {
      printf(" `%s'", cmd.argv[i]);
    }
    printf("\n");
  }
}
/**********************************************************************/

void
usage(void)
{
  fprintf(stderr, "usage: %s%s", Program, "\
 [-pkmb] [-ebpp] [-nobary] [-DE405] [-xwin] [-dm dm] [-n proflen] [-nsub nsub] [-npart npart] [-pstep pstep] [-pdstep pdstep] [-dmstep dmstep] [-npfact npfact] [-ndmfact ndmfact] [-p p] [-pd pd] [-pdd pdd] [-f f] [-fd fd] [-fdd fdd] [-phs phs] [-start startT] [-end endT] [-psr psrname] [-obs obscode] [-rzwcand rzwcand] [-rzwfile rzwfile] [-bin] [-pb pb] [-x asinic] [-e e] [-To To] [-w w] [-wdot wdot] [--] infile\n\
    Prepares a raw, multichannel, radio data file and folds it looking for the correct dispersion measure.\n\
     -pkmb: Raw data in Parkes Multibeam format\n\
     -ebpp: Raw data in Effelsberg-Berkeley Pulsar Processor format.  CURRENTLY UNSUPPORTED\n\
   -nobary: Do not barycenter (assume input parameters are topocentric)\n\
    -DE405: Use the DE405 ephemeris for barycentering instead of DE200 (the default)\n\
     -xwin: Show the result plots on-screen as well as make a plotfile\n\
       -dm: The central DM of the search (cm^-3 pc)\n\
            1 double value between 0 and oo\n\
            default: `0'\n\
        -n: The number of bins in the profile.  Defaults to the number of sampling bins which correspond to one folded period\n\
            1 int value\n\
     -nsub: The number of sub-bands to use for the DM search\n\
            1 int value between 1 and 512\n\
            default: `32'\n\
    -npart: The number of sub-integrations to use for the period search\n\
            1 int value between 1 and 512\n\
            default: `64'\n\
    -pstep: The minimum period stepsize over the observation in profile bins\n\
            1 int value between 1 and 10\n\
            default: `2'\n\
   -pdstep: The minimum P-dot stepsize over the observation in profile bins\n\
            1 int value between 1 and 20\n\
            default: `4'\n\
   -dmstep: The minimum DM stepsize over the observation in profile bins\n\
            1 int value between 1 and 10\n\
            default: `2'\n\
   -npfact: 2 * npfact * proflen + 1 periods and p-dots will be searched\n\
            1 int value between 1 and 10\n\
            default: `2'\n\
  -ndmfact: 2 * ndmfact * proflen + 1 DMs will be searched\n\
            1 int value between 1 and 10\n\
            default: `3'\n\
        -p: The nominative folding period (s)\n\
            1 double value between 0 and oo\n\
       -pd: The nominative period derivative (s/s)\n\
            1 double value\n\
            default: `0.0'\n\
      -pdd: The nominative period 2nd derivative (s/s^2)\n\
            1 double value\n\
            default: `0.0'\n\
        -f: The nominative folding frequency (hz)\n\
            1 double value between 0 and oo\n\
       -fd: The nominative frequency derivative (hz/s)\n\
            1 double value\n\
            default: `0'\n\
      -fdd: The nominative frequency 2nd derivative (hz/s^2)\n\
            1 double value\n\
            default: `0'\n\
      -phs: Offset phase for the profil\n\
            1 double value between 0.0 and 1.0\n\
            default: `0.0'\n\
    -start: The folding start time as a fraction of the full obs\n\
            1 double value between 0.0 and 1.0\n\
            default: `0.0'\n\
      -end: The folding end time as a fraction of the full obs\n\
            1 double value between 0.0 and 1.0\n\
            default: `1.0'\n\
      -psr: Name of pulsar to fold (do not include J or B)\n\
            1 char* value\n\
      -obs: Two letter TEMPO observatory code (for barycentering)\n\
            1 char* value\n\
  -rzwcand: The candidate number to fold from 'infile'_rzw.cand\n\
            1 int value between 1 and oo\n\
  -rzwfile: Name of the rzw search file to use (include the full name of the file)\n\
            1 char* value\n\
      -bin: Fold a binary pulsar.  Must include all of the following parameters\n\
       -pb: The orbital period (s)\n\
            1 double value between 0 and oo\n\
        -x: The projected orbital semi-major axis (lt-sec)\n\
            1 double value between 0 and oo\n\
        -e: The orbital eccentricity\n\
            1 double value between 0 and 0.9999999\n\
            default: `0'\n\
       -To: The time of periastron passage (MJD)\n\
            1 double value between 0 and oo\n\
        -w: Longitude of periastron (deg)\n\
            1 double value between 0 and 360\n\
     -wdot: Rate of advance of periastron (deg/yr)\n\
            1 double value\n\
            default: `0'\n\
    infile: Input data file name.  If the data is not in PKMB or EBPP format, it should be a single channel of single-precision floating point data.  In this case a '.inf' file with the same root filename must also exist (Note that this means that the input data file must have a suffix that starts with a period)\n\
            1 value\n\
version: 06Dec00\n\
");
  exit(EXIT_FAILURE);
}
/**********************************************************************/
Cmdline *
parseCmdline(int argc, char **argv)
{
  int i, keep;

  Program = argv[0];
  cmd.full_cmd_line = catArgv(argc, argv);
  for(i=1, cmd.argc=1; i<argc; i++) {
    if( 0==strcmp("--", argv[i]) ) {
      while( ++i<argc ) argv[cmd.argc++] = argv[i];
      continue;
    }

    if( 0==strcmp("-pkmb", argv[i]) ) {
      cmd.pkmbP = 1;
      continue;
    }

    if( 0==strcmp("-ebpp", argv[i]) ) {
      cmd.ebppP = 1;
      continue;
    }

    if( 0==strcmp("-nobary", argv[i]) ) {
      cmd.nobaryP = 1;
      continue;
    }

    if( 0==strcmp("-DE405", argv[i]) ) {
      cmd.de405P = 1;
      continue;
    }

    if( 0==strcmp("-xwin", argv[i]) ) {
      cmd.xwinP = 1;
      continue;
    }

    if( 0==strcmp("-dm", argv[i]) ) {
      cmd.dmP = 1;
      keep = i;
      i = getDoubleOpt(argc, argv, i, &cmd.dm, 1);
      cmd.dmC = i-keep;
      checkDoubleHigher("-dm", &cmd.dm, cmd.dmC, 0);
      continue;
    }

    if( 0==strcmp("-n", argv[i]) ) {
      cmd.proflenP = 1;
      keep = i;
      i = getIntOpt(argc, argv, i, &cmd.proflen, 1);
      cmd.proflenC = i-keep;
      continue;
    }

    if( 0==strcmp("-nsub", argv[i]) ) {
      cmd.nsubP = 1;
      keep = i;
      i = getIntOpt(argc, argv, i, &cmd.nsub, 1);
      cmd.nsubC = i-keep;
      checkIntLower("-nsub", &cmd.nsub, cmd.nsubC, 512);
      checkIntHigher("-nsub", &cmd.nsub, cmd.nsubC, 1);
      continue;
    }

    if( 0==strcmp("-npart", argv[i]) ) {
      cmd.npartP = 1;
      keep = i;
      i = getIntOpt(argc, argv, i, &cmd.npart, 1);
      cmd.npartC = i-keep;
      checkIntLower("-npart", &cmd.npart, cmd.npartC, 512);
      checkIntHigher("-npart", &cmd.npart, cmd.npartC, 1);
      continue;
    }

    if( 0==strcmp("-pstep", argv[i]) ) {
      cmd.pstepP = 1;
      keep = i;
      i = getIntOpt(argc, argv, i, &cmd.pstep, 1);
      cmd.pstepC = i-keep;
      checkIntLower("-pstep", &cmd.pstep, cmd.pstepC, 10);
      checkIntHigher("-pstep", &cmd.pstep, cmd.pstepC, 1);
      continue;
    }

    if( 0==strcmp("-pdstep", argv[i]) ) {
      cmd.pdstepP = 1;
      keep = i;
      i = getIntOpt(argc, argv, i, &cmd.pdstep, 1);
      cmd.pdstepC = i-keep;
      checkIntLower("-pdstep", &cmd.pdstep, cmd.pdstepC, 20);
      checkIntHigher("-pdstep", &cmd.pdstep, cmd.pdstepC, 1);
      continue;
    }

    if( 0==strcmp("-dmstep", argv[i]) ) {
      cmd.dmstepP = 1;
      keep = i;
      i = getIntOpt(argc, argv, i, &cmd.dmstep, 1);
      cmd.dmstepC = i-keep;
      checkIntLower("-dmstep", &cmd.dmstep, cmd.dmstepC, 10);
      checkIntHigher("-dmstep", &cmd.dmstep, cmd.dmstepC, 1);
      continue;
    }

    if( 0==strcmp("-npfact", argv[i]) ) {
      cmd.npfactP = 1;
      keep = i;
      i = getIntOpt(argc, argv, i, &cmd.npfact, 1);
      cmd.npfactC = i-keep;
      checkIntLower("-npfact", &cmd.npfact, cmd.npfactC, 10);
      checkIntHigher("-npfact", &cmd.npfact, cmd.npfactC, 1);
      continue;
    }

    if( 0==strcmp("-ndmfact", argv[i]) ) {
      cmd.ndmfactP = 1;
      keep = i;
      i = getIntOpt(argc, argv, i, &cmd.ndmfact, 1);
      cmd.ndmfactC = i-keep;
      checkIntLower("-ndmfact", &cmd.ndmfact, cmd.ndmfactC, 10);
      checkIntHigher("-ndmfact", &cmd.ndmfact, cmd.ndmfactC, 1);
      continue;
    }

    if( 0==strcmp("-p", argv[i]) ) {
      cmd.pP = 1;
      keep = i;
      i = getDoubleOpt(argc, argv, i, &cmd.p, 1);
      cmd.pC = i-keep;
      checkDoubleHigher("-p", &cmd.p, cmd.pC, 0);
      continue;
    }

    if( 0==strcmp("-pd", argv[i]) ) {
      cmd.pdP = 1;
      keep = i;
      i = getDoubleOpt(argc, argv, i, &cmd.pd, 1);
      cmd.pdC = i-keep;
      continue;
    }

    if( 0==strcmp("-pdd", argv[i]) ) {
      cmd.pddP = 1;
      keep = i;
      i = getDoubleOpt(argc, argv, i, &cmd.pdd, 1);
      cmd.pddC = i-keep;
      continue;
    }

    if( 0==strcmp("-f", argv[i]) ) {
      cmd.fP = 1;
      keep = i;
      i = getDoubleOpt(argc, argv, i, &cmd.f, 1);
      cmd.fC = i-keep;
      checkDoubleHigher("-f", &cmd.f, cmd.fC, 0);
      continue;
    }

    if( 0==strcmp("-fd", argv[i]) ) {
      cmd.fdP = 1;
      keep = i;
      i = getDoubleOpt(argc, argv, i, &cmd.fd, 1);
      cmd.fdC = i-keep;
      continue;
    }

    if( 0==strcmp("-fdd", argv[i]) ) {
      cmd.fddP = 1;
      keep = i;
      i = getDoubleOpt(argc, argv, i, &cmd.fdd, 1);
      cmd.fddC = i-keep;
      continue;
    }

    if( 0==strcmp("-phs", argv[i]) ) {
      cmd.phsP = 1;
      keep = i;
      i = getDoubleOpt(argc, argv, i, &cmd.phs, 1);
      cmd.phsC = i-keep;
      checkDoubleLower("-phs", &cmd.phs, cmd.phsC, 1.0);
      checkDoubleHigher("-phs", &cmd.phs, cmd.phsC, 0.0);
      continue;
    }

    if( 0==strcmp("-start", argv[i]) ) {
      cmd.startTP = 1;
      keep = i;
      i = getDoubleOpt(argc, argv, i, &cmd.startT, 1);
      cmd.startTC = i-keep;
      checkDoubleLower("-start", &cmd.startT, cmd.startTC, 1.0);
      checkDoubleHigher("-start", &cmd.startT, cmd.startTC, 0.0);
      continue;
    }

    if( 0==strcmp("-end", argv[i]) ) {
      cmd.endTP = 1;
      keep = i;
      i = getDoubleOpt(argc, argv, i, &cmd.endT, 1);
      cmd.endTC = i-keep;
      checkDoubleLower("-end", &cmd.endT, cmd.endTC, 1.0);
      checkDoubleHigher("-end", &cmd.endT, cmd.endTC, 0.0);
      continue;
    }

    if( 0==strcmp("-psr", argv[i]) ) {
      cmd.psrnameP = 1;
      keep = i;
      i = getStringOpt(argc, argv, i, &cmd.psrname, 1);
      cmd.psrnameC = i-keep;
      continue;
    }

    if( 0==strcmp("-obs", argv[i]) ) {
      cmd.obscodeP = 1;
      keep = i;
      i = getStringOpt(argc, argv, i, &cmd.obscode, 1);
      cmd.obscodeC = i-keep;
      continue;
    }

    if( 0==strcmp("-rzwcand", argv[i]) ) {
      cmd.rzwcandP = 1;
      keep = i;
      i = getIntOpt(argc, argv, i, &cmd.rzwcand, 1);
      cmd.rzwcandC = i-keep;
      checkIntHigher("-rzwcand", &cmd.rzwcand, cmd.rzwcandC, 1);
      continue;
    }

    if( 0==strcmp("-rzwfile", argv[i]) ) {
      cmd.rzwfileP = 1;
      keep = i;
      i = getStringOpt(argc, argv, i, &cmd.rzwfile, 1);
      cmd.rzwfileC = i-keep;
      continue;
    }

    if( 0==strcmp("-bin", argv[i]) ) {
      cmd.binaryP = 1;
      continue;
    }

    if( 0==strcmp("-pb", argv[i]) ) {
      cmd.pbP = 1;
      keep = i;
      i = getDoubleOpt(argc, argv, i, &cmd.pb, 1);
      cmd.pbC = i-keep;
      checkDoubleHigher("-pb", &cmd.pb, cmd.pbC, 0);
      continue;
    }

    if( 0==strcmp("-x", argv[i]) ) {
      cmd.asinicP = 1;
      keep = i;
      i = getDoubleOpt(argc, argv, i, &cmd.asinic, 1);
      cmd.asinicC = i-keep;
      checkDoubleHigher("-x", &cmd.asinic, cmd.asinicC, 0);
      continue;
    }

    if( 0==strcmp("-e", argv[i]) ) {
      cmd.eP = 1;
      keep = i;
      i = getDoubleOpt(argc, argv, i, &cmd.e, 1);
      cmd.eC = i-keep;
      checkDoubleLower("-e", &cmd.e, cmd.eC, 0.9999999);
      checkDoubleHigher("-e", &cmd.e, cmd.eC, 0);
      continue;
    }

    if( 0==strcmp("-To", argv[i]) ) {
      cmd.ToP = 1;
      keep = i;
      i = getDoubleOpt(argc, argv, i, &cmd.To, 1);
      cmd.ToC = i-keep;
      checkDoubleHigher("-To", &cmd.To, cmd.ToC, 0);
      continue;
    }

    if( 0==strcmp("-w", argv[i]) ) {
      cmd.wP = 1;
      keep = i;
      i = getDoubleOpt(argc, argv, i, &cmd.w, 1);
      cmd.wC = i-keep;
      checkDoubleLower("-w", &cmd.w, cmd.wC, 360);
      checkDoubleHigher("-w", &cmd.w, cmd.wC, 0);
      continue;
    }

    if( 0==strcmp("-wdot", argv[i]) ) {
      cmd.wdotP = 1;
      keep = i;
      i = getDoubleOpt(argc, argv, i, &cmd.wdot, 1);
      cmd.wdotC = i-keep;
      continue;
    }

    if( argv[i][0]=='-' ) {
      fprintf(stderr, "\n%s: unknown option `%s'\n\n",
              Program, argv[i]);
      usage();
    }
    argv[cmd.argc++] = argv[i];
  }/* for i */


  /*@-mustfree*/
  cmd.argv = argv+1;
  /*@=mustfree*/
  cmd.argc -= 1;

  if( 1>cmd.argc ) {
    fprintf(stderr, "%s: there should be at least 1 non-option argument(s)\n",
            Program);
    exit(EXIT_FAILURE);
  }
  if( 1<cmd.argc ) {
    fprintf(stderr, "%s: there should be at most 1 non-option argument(s)\n",
            Program);
    exit(EXIT_FAILURE);
  }
  /*@-compmempass*/  return &cmd;
}

