/*****
  Command line parser for prepfold_multi.

  This is a hand-written parser (the clig code generator is not available in
  this build environment).  It populates the SAME struct s_Cmdline layout that
  prepfold uses -- prepfold_multi_cmd.h is prepfold_cmd.h with a single
  `candfile` field appended AFTER full_cmd_line, so every field the shared
  prepfold_pipeline.c code touches keeps prepfold's offsets.  prepfold_multi
  therefore exposes only the options that make sense when folding many
  candidates from a file; the single-candidate spin/source/binary/event options
  remain in the struct (defaulted, never set) so the shared pipeline compiles
  and links unchanged.
*****/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "prepfold_multi_cmd.h"

char *Program;

static Cmdline cmd;

void usage(void)
{
    printf(
"  Usage: prepfold_multi -candfile FILE [options] infile(s)\n"
"\n"
"  Folds many pulsar candidates -- each with its own period/frequency,\n"
"  derivatives, and DM -- in a single pass over the raw data.  The raw data\n"
"  are read once; dedispersion and folding are done per candidate.\n"
"\n"
"  Input data must be raw radio data (PSRFITS or SIGPROC filterbank) or PRESTO\n"
"  subbands (*.subNN).  Already-dedispersed .dat time series and event files\n"
"  are not supported (there is no per-candidate DM for them); use prepfold.\n"
"\n"
"  Candidate file format (whitespace-delimited, '#' starts a comment):\n"
"    The first non-blank line is a header beginning with '#' that names the\n"
"    columns.  Recognized keys (case-insensitive, any order):\n"
"      name           candidate name (optional; autogenerated if absent)\n"
"      DM             dispersion measure, cm^-3 pc (required)\n"
"      p   | f        spin period (s) OR spin frequency (Hz)            (one required)\n"
"      pd  | fd       period (s/s) OR frequency (Hz/s) derivative       (optional, 0.0)\n"
"      pdd | fdd      period (s/s^2) OR frequency (Hz/s^2) 2nd deriv     (optional, 0.0)\n"
"    p/pd/pdd are mutually exclusive with f/fd/fdd (no mixing in one file).\n"
"    Example:\n"
"      # name        DM      p            pd     pdd\n"
"      J1748-2446A   242.30  0.0057360919 0.0    0.0\n"
"    See the prepfold_multi(1) man page for the full candidate-file format.\n"
"\n"
"  Options (shared with prepfold):\n"
"    -candfile FILE  Candidate list described above (required)\n"
"    -o ROOT         Root of the output file names\n"
"    -filterbank     Raw data in SIGPROC filterbank format\n"
"    -psrfits        Raw data in PSRFITS format\n"
"    -noweights      Do not apply PSRFITS weights\n"
"    -noscales       Do not apply PSRFITS scales\n"
"    -nooffsets      Do not apply PSRFITS offsets\n"
"    -topo           Fold topocentrically (i.e. don't barycenter)\n"
"    -invert         For rawdata, flip (invert) the band\n"
"    -zerodm         Subtract the mean of all channels from each sample\n"
"    -samples        Treat the data as samples, not integrated data\n"
"    -normalize      Bandpass flatten by normalizing the subbands\n"
"    -if IF          A specific IF to use if available (0 or 1)\n"
"    -clip SIGMA     Time-domain sigma for clipping (0.0 = none, default 6.0)\n"
"    -noclip         Do not clip the data\n"
"    -noxwin         Only make postscript files, no on-screen plots\n"
"    -runavg         Subtract each block's average as it is read\n"
"    -fine           Finer p/pdot gridding (well-known p and pdot)\n"
"    -coarse         Coarser p/pdot gridding (unknown p and pdot)\n"
"    -slow           Sets useful flags for slow pulsars\n"
"    -searchpdd      Search p-dotdots as well as p and p-dots\n"
"    -searchfdd      Search f-dotdots as well as f and f-dots\n"
"    -nosearch       Show but do not search the p/pdot and/or DM spaces\n"
"    -nopsearch      Show but do not search over period\n"
"    -nopdsearch     Show but do not search over p-dot\n"
"    -nodmsearch     Show but do not search over DM\n"
"    -scaleparts     Scale the part profiles independently\n"
"    -allgrey        Make all the images greyscale\n"
"    -fixchi         Adjust reduced chi^2 so off-pulse reduced chi^2 = 1\n"
"    -justprofs      Only output the profile portions of the plot\n"
"    -n BINS         Profile bins applied to ALL candidates (default: chosen\n"
"                    automatically per candidate from its period)\n"
"    -nsub SUBBANDS  Number of sub-bands for the DM search (1-4096)\n"
"    -npart PARTS    Number of sub-integrations for the period search\n"
"    -pstep BINS     Minimum period stepsize (profile bins)\n"
"    -pdstep BINS    Minimum P-dot stepsize (profile bins)\n"
"    -dmstep BINS    Minimum DM stepsize (profile bins)\n"
"    -npfact N       2*npfact*proflen+1 periods/p-dots searched\n"
"    -ndmfact N      2*ndmfact*proflen+1 DMs searched\n"
"    -phs PHASE      Offset phase for the profiles (0.0-1.0)\n"
"    -start FRAC     Folding start time as a fraction of the obs (0.0-1.0)\n"
"    -end FRAC       Folding end time as a fraction of the obs (0.0-1.0)\n"
"    -mask FILE      File containing rfifind masking information\n"
"    -ignorechan STR Comma-separated channels to ignore (min:max[:step])\n"
"    infile(s)       Input data file name(s)\n"
"\n");
}

void showOptionValues(void)
{
    /* Debug stub; the clig-generated version dumps every option. */
    printf("prepfold_multi: candfile = '%s'\n",
           cmd.candfileP ? cmd.candfile : "(none)");
}

/* Report a fatal command-line error, show usage, and exit. */
static void cmdline_error(const char *msg, const char *arg)
{
    fprintf(stderr, "\nprepfold_multi: %s", msg);
    if (arg)
        fprintf(stderr, " '%s'", arg);
    fprintf(stderr, "\n\n");
    usage();
    exit(1);
}

/* Fetch the value argument that must follow a value-taking option. */
static char *need_value(int argc, char **argv, int *ip, const char *opt)
{
    if (*ip + 1 >= argc)
        cmdline_error("missing value for option", opt);
    return argv[++(*ip)];
}

static int parse_int(const char *s, const char *opt)
{
    char *end;
    long v = strtol(s, &end, 10);
    if (end == s || *end != '\0')
        cmdline_error("expected an integer for option", opt);
    return (int) v;
}

static double parse_double(const char *s, const char *opt)
{
    char *end;
    double v = strtod(s, &end);
    if (end == s || *end != '\0')
        cmdline_error("expected a number for option", opt);
    return v;
}

Cmdline *parseCmdline(int argc, char **argv)
{
    int ii;
    char **files;
    int numfiles = 0;
    size_t cmdlen = 0;

    /* Defaults (matching the clig -d values prepfold uses) */
    memset(&cmd, 0, sizeof(cmd));
    cmd.ncpus = 1;      cmd.ncpusP = 1;     cmd.ncpusC = 1;
    cmd.clip = 6.0;
    cmd.npart = 64;
    cmd.pstep = 2;      cmd.pdstep = 4;     cmd.dmstep = 2;
    cmd.npfact = 2;     cmd.ndmfact = 3;
    cmd.pfact = 1.0;    cmd.ffact = 1.0;
    cmd.phs = 0.0;
    cmd.startT = 0.0;   cmd.endT = 1.0;
    cmd.numwapps = 1;

    files = (char **) malloc(sizeof(char *) * (argc > 0 ? argc : 1));

    for (ii = 1; ii < argc; ii++) {
        char *a = argv[ii];

        if (a[0] != '-' || a[1] == '\0') {      /* not an option -> input file */
            files[numfiles++] = a;
            continue;
        }
        /* Allow negative numbers as positional args (none expected, but safe) */
        if ((a[1] >= '0' && a[1] <= '9') || a[1] == '.') {
            files[numfiles++] = a;
            continue;
        }

        /* ---- Flags (no argument) ---- */
        if      (!strcmp(a, "-filterbank")) cmd.filterbankP = 1;
        else if (!strcmp(a, "-psrfits"))    cmd.psrfitsP = 1;
        else if (!strcmp(a, "-noweights"))  cmd.noweightsP = 1;
        else if (!strcmp(a, "-noscales"))   cmd.noscalesP = 1;
        else if (!strcmp(a, "-nooffsets"))  cmd.nooffsetsP = 1;
        else if (!strcmp(a, "-topo"))       cmd.topoP = 1;
        else if (!strcmp(a, "-invert"))     cmd.invertP = 1;
        else if (!strcmp(a, "-zerodm"))     cmd.zerodmP = 1;
        else if (!strcmp(a, "-samples"))    cmd.samplesP = 1;
        else if (!strcmp(a, "-normalize"))  cmd.normalizeP = 1;
        else if (!strcmp(a, "-noclip"))     cmd.noclipP = 1;
        else if (!strcmp(a, "-noxwin"))     cmd.noxwinP = 1;
        else if (!strcmp(a, "-runavg"))     cmd.runavgP = 1;
        else if (!strcmp(a, "-fine"))       cmd.fineP = 1;
        else if (!strcmp(a, "-coarse"))     cmd.coarseP = 1;
        else if (!strcmp(a, "-slow"))       cmd.slowP = 1;
        else if (!strcmp(a, "-searchpdd"))  cmd.searchpddP = 1;
        else if (!strcmp(a, "-searchfdd"))  cmd.searchfddP = 1;
        else if (!strcmp(a, "-nosearch"))   cmd.nosearchP = 1;
        else if (!strcmp(a, "-nopsearch"))  cmd.nopsearchP = 1;
        else if (!strcmp(a, "-nopdsearch")) cmd.nopdsearchP = 1;
        else if (!strcmp(a, "-nodmsearch")) cmd.nodmsearchP = 1;
        else if (!strcmp(a, "-scaleparts")) cmd.scalepartsP = 1;
        else if (!strcmp(a, "-allgrey"))    cmd.allgreyP = 1;
        else if (!strcmp(a, "-fixchi"))     cmd.fixchiP = 1;
        else if (!strcmp(a, "-justprofs"))  cmd.justprofsP = 1;

        /* ---- Int-valued options ---- */
        else if (!strcmp(a, "-ncpus")) {
            cmd.ncpus = parse_int(need_value(argc, argv, &ii, a), a); cmd.ncpusP = 1;
        } else if (!strcmp(a, "-if")) {
            cmd.ifs = parse_int(need_value(argc, argv, &ii, a), a); cmd.ifsP = 1;
        } else if (!strcmp(a, "-n")) {
            cmd.proflen = parse_int(need_value(argc, argv, &ii, a), a); cmd.proflenP = 1;
        } else if (!strcmp(a, "-nsub")) {
            cmd.nsub = parse_int(need_value(argc, argv, &ii, a), a); cmd.nsubP = 1;
        } else if (!strcmp(a, "-npart")) {
            cmd.npart = parse_int(need_value(argc, argv, &ii, a), a); cmd.npartP = 1;
        } else if (!strcmp(a, "-pstep")) {
            cmd.pstep = parse_int(need_value(argc, argv, &ii, a), a); cmd.pstepP = 1;
        } else if (!strcmp(a, "-pdstep")) {
            cmd.pdstep = parse_int(need_value(argc, argv, &ii, a), a); cmd.pdstepP = 1;
        } else if (!strcmp(a, "-dmstep")) {
            cmd.dmstep = parse_int(need_value(argc, argv, &ii, a), a); cmd.dmstepP = 1;
        } else if (!strcmp(a, "-npfact")) {
            cmd.npfact = parse_int(need_value(argc, argv, &ii, a), a); cmd.npfactP = 1;
        } else if (!strcmp(a, "-ndmfact")) {
            cmd.ndmfact = parse_int(need_value(argc, argv, &ii, a), a); cmd.ndmfactP = 1;
        }

        /* ---- Float/Double-valued options ---- */
        else if (!strcmp(a, "-clip")) {
            cmd.clip = (float) parse_double(need_value(argc, argv, &ii, a), a); cmd.clipP = 1;
        } else if (!strcmp(a, "-phs")) {
            cmd.phs = parse_double(need_value(argc, argv, &ii, a), a); cmd.phsP = 1;
        } else if (!strcmp(a, "-start")) {
            cmd.startT = parse_double(need_value(argc, argv, &ii, a), a); cmd.startTP = 1;
        } else if (!strcmp(a, "-end")) {
            cmd.endT = parse_double(need_value(argc, argv, &ii, a), a); cmd.endTP = 1;
        }

        /* ---- String-valued options ---- */
        else if (!strcmp(a, "-o")) {
            cmd.outfile = need_value(argc, argv, &ii, a); cmd.outfileP = 1;
        } else if (!strcmp(a, "-mask")) {
            cmd.maskfile = need_value(argc, argv, &ii, a); cmd.maskfileP = 1;
        } else if (!strcmp(a, "-ignorechan")) {
            cmd.ignorechanstr = need_value(argc, argv, &ii, a); cmd.ignorechanstrP = 1;
        } else if (!strcmp(a, "-candfile")) {
            cmd.candfile = need_value(argc, argv, &ii, a); cmd.candfileP = 1;
        }

        else {
            cmdline_error("unknown option", a);
        }
    }

    cmd.argv = files;
    cmd.argc = numfiles;

    /* Rebuild the full command line for the .pfd record. */
    for (ii = 0; ii < argc; ii++)
        cmdlen += strlen(argv[ii]) + 1;
    cmd.full_cmd_line = (char *) calloc(cmdlen + 1, sizeof(char));
    for (ii = 0; ii < argc; ii++) {
        strcat(cmd.full_cmd_line, argv[ii]);
        if (ii < argc - 1)
            strcat(cmd.full_cmd_line, " ");
    }

    /* ---- Validation ---- */
    if (!cmd.candfileP)
        cmdline_error("a candidate file is required (-candfile FILE)", NULL);
    if (numfiles < 1)
        cmdline_error("at least one input data file is required", NULL);
    if (cmd.nsubP && (cmd.nsub < 1 || cmd.nsub > 4096))
        cmdline_error("-nsub must be between 1 and 4096", NULL);
    if (cmd.npart < 1)
        cmdline_error("-npart must be >= 1", NULL);
    if (cmd.startT < 0.0 || cmd.startT > 1.0)
        cmdline_error("-start must be between 0.0 and 1.0", NULL);
    if (cmd.endT < 0.0 || cmd.endT > 1.0)
        cmdline_error("-end must be between 0.0 and 1.0", NULL);
    if (cmd.endT <= cmd.startT)
        cmdline_error("-end must be greater than -start", NULL);

    return &cmd;
}
