/****
  command line parser -- generated by pyclig
  (https://github.com/scottransom/pyCLIG)

  Based on the original clig by Harald Kirsch:
  (C) 1995-2004 Harald Kirsch (clig@geggus.net)
  pyCLIG (C) 2026 Scott Ransom and Claude (Anthropic)
****/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <errno.h>
#include <limits.h>
#include <float.h>
#include <math.h>

#include "rednoise_cmd.h"

char *Program;

static Cmdline cmd = {
    /***** -startwidth: The initial windowing size. */
    /* startwidthP = */ 1,
    /* startwidth = */ 6,
    /* startwidthC = */ 1,
    /***** -endwidth: The final windowing size. */
    /* endwidthP = */ 1,
    /* endwidth = */ 100,
    /* endwidthC = */ 1,
    /***** -endfreq: The highest frequency where the windowing increases. */
    /* endfreqP = */ 1,
    /* endfreq = */ 6,
    /* endfreqC = */ 1,
    /***** -inplace: Deredden the input file in place, renaming it, rather than writing a second copy */
    /* inplaceP = */ 0,
    /***** uninterpreted rest of command line */
    /* argc = */ 0,
    /* argv = */ NULL,
    /***** the original command line concatenated */
    /* full_cmd_line = */ NULL
};

/*********************************************************************/

int getIntOpt(int argc, char **argv, int i, int *value, int force)
{
    char *end;
    long v;

    if (++i >= argc)
        goto nothingFound;

    errno = 0;
    v = strtol(argv[i], &end, 0);

    if (end == argv[i])
        goto nothingFound;

    while (isspace((unsigned char) *end))
        end++;
    if (*end)
        goto nothingFound;

    if (errno == ERANGE || v > (long) INT_MAX || v < (long) INT_MIN) {
        fprintf(stderr,
                "%s: parameter `%s' of option `%s' too large to represent\n",
                Program, argv[i], argv[i - 1]);
        exit(EXIT_FAILURE);
    }
    *value = (int) v;
    return i;

  nothingFound:
    if (!force)
        return i - 1;
    fprintf(stderr,
            "%s: missing or malformed integer value after option `%s'\n",
            Program, argv[i - 1]);
    exit(EXIT_FAILURE);
}

/*********************************************************************/

int getDoubleOpt(int argc, char **argv, int i, double *value, int force)
{
    char *end;

    if (++i >= argc)
        goto nothingFound;

    errno = 0;
    *value = strtod(argv[i], &end);

    if (end == argv[i])
        goto nothingFound;

    while (isspace((unsigned char) *end))
        end++;
    if (*end)
        goto nothingFound;

    if (errno == ERANGE) {
        fprintf(stderr,
                "%s: parameter `%s' of option `%s' too %s to represent\n",
                Program, argv[i], argv[i - 1], (*value == 0.0 ? "small" : "large"));
        exit(EXIT_FAILURE);
    }
    return i;

  nothingFound:
    if (!force)
        return i - 1;
    fprintf(stderr,
            "%s: missing or malformed value after option `%s'\n",
            Program, argv[i - 1]);
    exit(EXIT_FAILURE);
}

/*********************************************************************/

void checkIntLower(const char *opt, int *values, int count, int max)
{
    int i;
    for (i = 0; i < count; i++) {
        if (values[i] <= max)
            continue;
        fprintf(stderr,
                "%s: parameter %d of option `%s' greater than max=%d\n",
                Program, i + 1, opt, max);
        exit(EXIT_FAILURE);
    }
}

/*********************************************************************/

void checkIntHigher(const char *opt, int *values, int count, int min)
{
    int i;
    for (i = 0; i < count; i++) {
        if (values[i] >= min)
            continue;
        fprintf(stderr,
                "%s: parameter %d of option `%s' smaller than min=%d\n",
                Program, i + 1, opt, min);
        exit(EXIT_FAILURE);
    }
}

/*********************************************************************/

void checkDoubleLower(const char *opt, double *values, int count, double max)
{
    int i;
    for (i = 0; i < count; i++) {
        if (values[i] <= max)
            continue;
        fprintf(stderr,
                "%s: parameter %d of option `%s' greater than max=%f\n",
                Program, i + 1, opt, max);
        exit(EXIT_FAILURE);
    }
}

/*********************************************************************/

void checkDoubleHigher(const char *opt, double *values, int count, double min)
{
    int i;
    for (i = 0; i < count; i++) {
        if (values[i] >= min)
            continue;
        fprintf(stderr,
                "%s: parameter %d of option `%s' smaller than min=%f\n",
                Program, i + 1, opt, min);
        exit(EXIT_FAILURE);
    }
}

/*********************************************************************/

static char *catArgv(int argc, char **argv)
{
    int i;
    size_t l, pos, n;
    char *s;

    for (i = 0, l = 1; i < argc; i++)
        l += strlen(argv[i]) + 1;
    s = (char *) malloc(l);
    if (!s) {
        fprintf(stderr, "%s: out of memory\n", Program);
        exit(EXIT_FAILURE);
    }
    for (i = 0, pos = 0; i < argc; i++) {
        n = strlen(argv[i]);
        if (i > 0)
            s[pos++] = ' ';
        memcpy(s + pos, argv[i], n);
        pos += n;
    }
    s[pos] = '\0';
    return s;
}

/*********************************************************************/

void showOptionValues(void)
{
    int i;

    printf("Full command line is:\n`%s'\n", cmd.full_cmd_line);

    /***** -startwidth: The initial windowing size. */
    if (!cmd.startwidthP) {
        printf("-startwidth not found.\n");
    } else {
        printf("-startwidth found:\n");
        if (!cmd.startwidthC) {
            printf("  no values\n");
        } else {
            printf("  value = `%d'\n", cmd.startwidth);
        }
    }

    /***** -endwidth: The final windowing size. */
    if (!cmd.endwidthP) {
        printf("-endwidth not found.\n");
    } else {
        printf("-endwidth found:\n");
        if (!cmd.endwidthC) {
            printf("  no values\n");
        } else {
            printf("  value = `%d'\n", cmd.endwidth);
        }
    }

    /***** -endfreq: The highest frequency where the windowing increases. */
    if (!cmd.endfreqP) {
        printf("-endfreq not found.\n");
    } else {
        printf("-endfreq found:\n");
        if (!cmd.endfreqC) {
            printf("  no values\n");
        } else {
            printf("  value = `%.40g'\n", cmd.endfreq);
        }
    }

    /***** -inplace: Deredden the input file in place, renaming it, rather than writing a second copy */
    if (!cmd.inplaceP) {
        printf("-inplace not found.\n");
    } else {
        printf("-inplace found:\n");
    }

    if (!cmd.argc) {
        printf("no remaining parameters in argv\n");
    } else {
        printf("argv =");
        for (i = 0; i < cmd.argc; i++)
            printf(" `%s'", cmd.argv[i]);
        printf("\n");
    }
}

/*********************************************************************/

void usage(void)
{
    fputs("   [-startwidth startwidth] [-endwidth endwidth] [-endfreq endfreq] [-inplace] [--] file\n", stderr);
    fputs("      Rednoise extraction routine.\n", stderr);
    fputs("    -startwidth: The initial windowing size.\n", stderr);
    fputs("                 1 int value between 2 and 50\n", stderr);
    fputs("                 default: `6'\n", stderr);
    fputs("      -endwidth: The final windowing size.\n", stderr);
    fputs("                 1 int value between 50 and 500\n", stderr);
    fputs("                 default: `100'\n", stderr);
    fputs("       -endfreq: The highest frequency where the windowing increases.\n", stderr);
    fputs("                 1 double value between 0.1 and 10\n", stderr);
    fputs("                 default: `6'\n", stderr);
    fputs("       -inplace: Deredden the input file in place, renaming it, rather than writing a second copy\n", stderr);
    fputs("           file: Input '.fft' file.\n", stderr);
    fputs("                 1 value\n", stderr);
    fputs("  CLI code generated: 20Aug26\n", stderr);
    fputs("  ", stderr);
    exit(EXIT_FAILURE);
}

/*********************************************************************/

Cmdline *parseCmdline(int argc, char **argv)
{
    int i;

    Program = argv[0];
    cmd.full_cmd_line = catArgv(argc, argv);
    for (i = 1, cmd.argc = 1; i < argc; i++) {

        if (0 == strcmp("--", argv[i])) {
            while (++i < argc)
                argv[cmd.argc++] = argv[i];
            continue;
        }

        if (0 == strcmp("-startwidth", argv[i])) {
            int keep = i;
            cmd.startwidthP = 1;
            i = getIntOpt(argc, argv, i, &cmd.startwidth, 1);
            cmd.startwidthC = i - keep;
            checkIntLower("-startwidth", &cmd.startwidth, cmd.startwidthC, 50);
            checkIntHigher("-startwidth", &cmd.startwidth, cmd.startwidthC, 2);
            continue;
        }

        if (0 == strcmp("-endwidth", argv[i])) {
            int keep = i;
            cmd.endwidthP = 1;
            i = getIntOpt(argc, argv, i, &cmd.endwidth, 1);
            cmd.endwidthC = i - keep;
            checkIntLower("-endwidth", &cmd.endwidth, cmd.endwidthC, 500);
            checkIntHigher("-endwidth", &cmd.endwidth, cmd.endwidthC, 50);
            continue;
        }

        if (0 == strcmp("-endfreq", argv[i])) {
            int keep = i;
            cmd.endfreqP = 1;
            i = getDoubleOpt(argc, argv, i, &cmd.endfreq, 1);
            cmd.endfreqC = i - keep;
            checkDoubleLower("-endfreq", &cmd.endfreq, cmd.endfreqC, 10);
            checkDoubleHigher("-endfreq", &cmd.endfreq, cmd.endfreqC, 0.1);
            continue;
        }

        if (0 == strcmp("-inplace", argv[i])) {
            cmd.inplaceP = 1;
            continue;
        }

        if (argv[i][0] == '-') {
            fprintf(stderr, "\n%s: unknown option `%s'\n\n",
                    Program, argv[i]);
            usage();
        }
        argv[cmd.argc++] = argv[i];
    }

    cmd.argv = argv + 1;
    cmd.argc -= 1;

    if (1 > cmd.argc) {
        fprintf(stderr,
                "%s: there should be at least 1 non-option argument(s)\n",
                Program);
        exit(EXIT_FAILURE);
    }
    if (1 < cmd.argc) {
        fprintf(stderr,
                "%s: there should be at most 1 non-option argument(s)\n",
                Program);
        exit(EXIT_FAILURE);
    }
    return &cmd;
}
