/*****
  command line parser -- generated by clig (Version: 1.1.3)

  The command line parser `clig':
  (C) 1995 Harald Kirsch (kir@iitb.fhg.de)
*****/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

/* mainly a hack to make things work on SUNOS with gcc */
extern double strtod(const char *, char **);
extern long int strtol(const char *, char **, int);

#include "search_rzw_cmd.h"

char *Program;

/*@-null*/

static Cmdline cmd = {
  /***** -ncand: Number of candidates to try to return */
  /* ncandP = */ TRUE,
  /* ncand = */ 100,
  /* ncandC = */ 1,
  /***** -zlo: The low Fourier frequency to check */
  /* zloP = */ TRUE,
  /* zlo = */ -50,
  /* zloC = */ 1,
  /***** -zhi: The high Fourier frequency to check */
  /* zhiP = */ TRUE,
  /* zhi = */ 50,
  /* zhiC = */ 1,
  /***** -rlo: The lowest Fourier frequency to check */
  /* rloP = */ TRUE,
  /* rlo = */ 300,
  /* rloC = */ 1,
  /***** -rhi: The highest Fourier frequency to check */
  /* rhiP = */ FALSE,
  /* rhi = */ (int)0,
  /* rhiC = */ 0,
  /***** -lobin: The first Fourier frequency in the data file */
  /* lobinP = */ TRUE,
  /* lobin = */ 0,
  /* lobinC = */ 1,
  /***** -zapfile: A file containing a list of freqs to ignore (i.e. RFI) */
  /* zapfileP = */ FALSE,
  /* zapfile = */ (char*)0,
  /* zapfileC = */ 0,
  /***** -baryv: The earth's radial velocity component (v/c) towards the observation (used to convert topocentric birdie freqs to barycentric) */
  /* baryvP = */ TRUE,
  /* baryv = */ 0.0,
  /* baryvC = */ 1,
  /***** uninterpreted rest of command line */
  /* argc = */ 0,
  /* argv = */ (char**)0,
  /***** the original command line concatenated */
  /* full_cmd_line = */ NULL
};

/*@=null*/

/***** let LCLint run more smoothly */
/*@-predboolothers*/
/*@-boolops*/


/**********************************************************************/
int
getIntOpt(int argc, char **argv, int i, int *value, int force)
{
  char *end;

  if( ++i>=argc ) goto nothingFound;

  *value = (int)strtol(argv[i], &end, 10);

  /***** check for conversion error */
  if( end==argv[i] ) goto nothingFound;

  /***** check for surplus non-whitespace */
  while( isspace(*end) ) end+=1;
  if( *end ) goto nothingFound;

  return i;

nothingFound:
  if( !force ) return i-1;

  fprintf(stderr, 
	  "%s: missing or malformed integer value after option `%s'\n",
	  Program, argv[i-1]);
    exit(EXIT_FAILURE);
}
/**********************************************************************/
int
getIntOpts(int argc, char **argv, int i, 
	   int **values,
	   int cmin, int cmax)
/*****
  We want to find at least cmin values and at most cmax values.
  cmax==-1 then means infinitely many are allowed.
*****/
{
  int alloced, used;
  char *end;

  if( i+cmin >= argc ) {
    fprintf(stderr, 
	    "%s: option `%s' wants at least %d parameters\n",
	    Program, argv[i], cmin);
    exit(EXIT_FAILURE);
  }

  /***** 
    alloc a bit more than cmin values. It does not hurt to have room
    for a bit more values than cmax.
  *****/
  alloced = cmin + 4;
  *values = (int*)calloc((size_t)alloced, sizeof(int));
  if( ! *values ) {
outMem:
    fprintf(stderr, 
	    "%s: out of memory while parsing option `%s'\n",
	    Program, argv[i]);
    exit(EXIT_FAILURE);
  }

  for(used=0; (cmax==-1 || used<cmax) && used+i+1<argc; used++) {
    if( used==alloced ) {
      alloced += 8;
      *values = (int *) realloc(*values, alloced*sizeof(int));
      if( !*values ) goto outMem;
    }

    (*values)[used] = (int)strtol(argv[used+i+1], &end, 10);

    /***** check for conversion error */
    if( end==argv[used+i+1] ) break;

    /***** check for surplus non-whitespace */
    while( isspace(*end) ) end+=1;
    if( *end ) break;
  }
    
  if( used<cmin ) {
    fprintf(stderr, 
	    "%s: parameter `%s' of `%s' should be an "
	    "integer value\n",
	    Program, argv[i+used+1], argv[i]);
    exit(EXIT_FAILURE);
  }

  return i+used;
}
/**********************************************************************/
int
getFloatOpt(int argc, char **argv, int i, double *value, int force)
{
  char *end;

  if( ++i>=argc ) goto nothingFound;

  *value = (double)strtod(argv[i], &end);

  /***** check for conversion error */
  if( end==argv[i] ) goto nothingFound;

  /***** check for surplus non-whitespace */
  while( isspace(*end) ) end+=1;
  if( *end ) goto nothingFound;

  return i;

nothingFound:
  if( !force ) return i-1;

  fprintf(stderr,
	  "%s: missing or malformed double value after option `%s'\n",
	  Program, argv[i-1]);
  exit(EXIT_FAILURE);
 
}
/**********************************************************************/
int
getFloatOpts(int argc, char **argv, int i, 
	   double **values,
	   int cmin, int cmax)
/*****
  We want to find at least cmin values and at most cmax values.
  cmax==-1 then means infinitely many are allowed.
*****/
{
  int alloced, used;
  char *end;

  if( i+cmin >= argc ) {
    fprintf(stderr, 
	    "%s: option `%s' wants at least %d parameters\n",
	    Program, argv[i], cmin);
    exit(EXIT_FAILURE);
  }

  /***** 
    alloc a bit more than cmin values.
  *****/
  alloced = cmin + 4;
  *values = (double*)calloc((size_t)alloced, sizeof(double));
  if( ! *values ) {
outMem:
    fprintf(stderr, 
	    "%s: out of memory while parsing option `%s'\n",
	    Program, argv[i]);
    exit(EXIT_FAILURE);
  }

  for(used=0; (cmax==-1 || used<cmax) && used+i+1<argc; used++) {
    if( used==alloced ) {
      alloced += 8;
      *values = (double *) realloc(*values, alloced*sizeof(double));
      if( !*values ) goto outMem;
    }

    (*values)[used] = (double)strtod(argv[used+i+1], &end);

    /***** check for conversion error */
    if( end==argv[used+i+1] ) break;

    /***** check for surplus non-whitespace */
    while( isspace(*end) ) end+=1;
    if( *end ) break;
  }
    
  if( used<cmin ) {
    fprintf(stderr, 
	    "%s: parameter `%s' of `%s' should be a "
	    "double precision value\n",
	    Program, argv[i+used+1], argv[i]);
    exit(EXIT_FAILURE);
  }

  return i+used;
}
/**********************************************************************/
int
getStringOpt(int argc, char **argv, int i, char **value, int force)
{
  if( ++i>=argc ) {
    fprintf(stderr, "%s: missing string after option `%s'\n",
            Program, argv[i-1]);
    exit(EXIT_FAILURE);
  }
  
  if( !force && argv[i+1][0] == '-' ) return i-1;
  *value = argv[i];
  return i;
}
/**********************************************************************/
int
getStringOpts(int argc, char **argv, int i, 
	   char*  **values,
	   int cmin, int cmax)
/*****
  We want to find at least cmin values and at most cmax values.
  cmax==-1 then means infinitely many are allowed.
*****/
{
  int alloced, used;

  if( i+cmin >= argc ) {
    fprintf(stderr, 
	    "%s: option `%s' wants at least %d parameters\n",
	    Program, argv[i], cmin);
    exit(EXIT_FAILURE);
  }

  alloced = cmin + 4;
    
  *values = (char**)calloc((size_t)alloced, sizeof(char*));
  if( ! *values ) {
outMem:
    fprintf(stderr, 
	    "%s: out of memory during parsing of option `%s'\n",
	    Program, argv[i]);
    exit(EXIT_FAILURE);
  }

  for(used=0; (cmax==-1 || used<cmax) && used+i+1<argc; used++) {
    if( used==alloced ) {
      alloced += 8;
      *values = (char **)realloc(*values, alloced*sizeof(char*));
      if( !*values ) goto outMem;
    }

    if( used>=cmin && argv[used+i+1][0]=='-' ) break;
    (*values)[used] = argv[used+i+1];
  }
    
  if( used<cmin ) {
    fprintf(stderr, 
    "%s: less than %d parameters for option `%s', only %d found\n",
	    Program, cmin, argv[i], used);
    exit(EXIT_FAILURE);
  }

  return i+used;
}
/**********************************************************************/
void
checkIntLower(char *opt, int *values, int count, int max)
{
  int i;

  for(i=0; i<count; i++) {
    if( values[i]<=max ) continue;
    fprintf(stderr, 
	    "%s: parameter %d of option `%s' greater than max=%d\n",
	    Program, i+1, opt, max);
    exit(EXIT_FAILURE);
  }
}
/**********************************************************************/
void
checkIntHigher(char *opt, int *values, int count, int min)
{
  int i;

  for(i=0; i<count; i++) {
    if( values[i]>=min ) continue;
    fprintf(stderr, 
	    "%s: parameter %d of option `%s' smaller than min=%d\n",
	    Program, i+1, opt, min);
    exit(EXIT_FAILURE);
  }
}
/**********************************************************************/
void
checkFloatLower(char *opt, double *values, int count, double max)
{
  int i;

  for(i=0; i<count; i++) {
    if( values[i]<=max ) continue;
    fprintf(stderr, 
	    "%s: parameter %d of option `%s' greater than max=%f\n",
	    Program, i+1, opt, max);
    exit(EXIT_FAILURE);
  }
}
/**********************************************************************/
void
checkFloatHigher(char *opt, double *values, int count, double min)
{
  int i;

  for(i=0; i<count; i++) {
    if( values[i]>=min ) continue;
    fprintf(stderr, 
	    "%s: parameter %d of option `%s' smaller than min=%f\n",
	    Program, i+1, opt, min);
    exit(EXIT_FAILURE);
  }
}
/**********************************************************************/
static char *
catArgv(int argc, char **argv)
{
  int i;
  size_t l;
  char *s, *t;

  for(i=0, l=0; i<argc; i++) l += (1+strlen(argv[i]));
  s = (char *)malloc(l);
  if( !s ) {
    fprintf(stderr, "%s: out of memory\n", Program);
    exit(EXIT_FAILURE);
  }
  strcpy(s, argv[0]);
  t = s;
  for(i=1; i<argc; i++) {
    t = t+strlen(t);
    *t++ = ' ';
    strcpy(t, argv[i]);
  }
  return s;
}
/**********************************************************************/
void
showOptionValues(void)
{
  int i;

  printf("Full command line is:\n`%s'\n", cmd.full_cmd_line);

  /***** -ncand: Number of candidates to try to return */
  if( !cmd.ncandP ) {
    printf("-ncand not found.\n");
  } else {
    printf("-ncand found:\n");
    if( !cmd.ncandC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%d'\n", cmd.ncand);
    }
  }

  /***** -zlo: The low Fourier frequency to check */
  if( !cmd.zloP ) {
    printf("-zlo not found.\n");
  } else {
    printf("-zlo found:\n");
    if( !cmd.zloC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%d'\n", cmd.zlo);
    }
  }

  /***** -zhi: The high Fourier frequency to check */
  if( !cmd.zhiP ) {
    printf("-zhi not found.\n");
  } else {
    printf("-zhi found:\n");
    if( !cmd.zhiC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%d'\n", cmd.zhi);
    }
  }

  /***** -rlo: The lowest Fourier frequency to check */
  if( !cmd.rloP ) {
    printf("-rlo not found.\n");
  } else {
    printf("-rlo found:\n");
    if( !cmd.rloC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%d'\n", cmd.rlo);
    }
  }

  /***** -rhi: The highest Fourier frequency to check */
  if( !cmd.rhiP ) {
    printf("-rhi not found.\n");
  } else {
    printf("-rhi found:\n");
    if( !cmd.rhiC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%d'\n", cmd.rhi);
    }
  }

  /***** -lobin: The first Fourier frequency in the data file */
  if( !cmd.lobinP ) {
    printf("-lobin not found.\n");
  } else {
    printf("-lobin found:\n");
    if( !cmd.lobinC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%d'\n", cmd.lobin);
    }
  }

  /***** -zapfile: A file containing a list of freqs to ignore (i.e. RFI) */
  if( !cmd.zapfileP ) {
    printf("-zapfile not found.\n");
  } else {
    printf("-zapfile found:\n");
    if( !cmd.zapfileC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%s'\n", cmd.zapfile);
    }
  }

  /***** -baryv: The earth's radial velocity component (v/c) towards the observation (used to convert topocentric birdie freqs to barycentric) */
  if( !cmd.baryvP ) {
    printf("-baryv not found.\n");
  } else {
    printf("-baryv found:\n");
    if( !cmd.baryvC ) {
      printf("  no values\n");
    } else {
      printf("  value = `%f'\n", cmd.baryv);
    }
  }
  if( !cmd.argc ) {
    printf("no remaining parameters in argv\n");
  } else {
    printf("argv =");
    for(i=0; i<cmd.argc; i++) {
      printf(" `%s'", cmd.argv[i]);
    }
    printf("\n");
  }
}
/**********************************************************************/

void
usage(void)
{
  fprintf(stderr, "usage: %s%s", Program, "\
 [-ncand ncand] [-zlo zlo] [-zhi zhi] [-rlo rlo] [-rhi rhi] [-lobin lobin] [-zapfile zapfile] [-baryv baryv] infile\n\
    Searches an FFT for pulsar candidates using a Fourier domain acceleration search.\n\
    -ncand: Number of candidates to try to return\n\
            1 integer value between 1 and 10000\n\
            default: `100'\n\
      -zlo: The low Fourier frequency to check\n\
            1 integer value between -2000000 and 2000000\n\
            default: `-50'\n\
      -zhi: The high Fourier frequency to check\n\
            1 integer value between -2000000 and 2000000\n\
            default: `50'\n\
      -rlo: The lowest Fourier frequency to check\n\
            1 integer value between 0 and oo\n\
            default: `300'\n\
      -rhi: The highest Fourier frequency to check\n\
            1 integer value between 0 and oo\n\
    -lobin: The first Fourier frequency in the data file\n\
            1 integer value between 0 and oo\n\
            default: `0'\n\
  -zapfile: A file containing a list of freqs to ignore (i.e. RFI)\n\
            1 string value\n\
    -baryv: The earth's radial velocity component (v/c) towards the observation (used to convert topocentric birdie freqs to barycentric)\n\
            1 double precision value between -0.1 and 0.1\n\
            default: `0.0'\n\
    infile: Input file name (no suffix) of floating point fft data.  A '.inf' file of the same name must also exist\n\
            1 string value\n\
version: 22Nov99\n\
");
  exit(EXIT_FAILURE);
}
/**********************************************************************/
Cmdline *
parseCmdline(int argc, char **argv)
{
  int i, keep;

  Program = argv[0];
  cmd.full_cmd_line = catArgv(argc, argv);
  for(i=1, cmd.argc=1; i<argc; i++) {
    if( 0==strcmp("--", argv[i]) ) {
      while( ++i<argc ) argv[cmd.argc++] = argv[i];
      continue;
    }

    if( 0==strcmp("-ncand", argv[i]) ) {
      cmd.ncandP = TRUE;
      keep = i;
      i = getIntOpt(argc, argv, i, &cmd.ncand, 1);
      cmd.ncandC = i-keep;
      checkIntLower("-ncand", &cmd.ncand, cmd.ncandC, 10000);
      checkIntHigher("-ncand", &cmd.ncand, cmd.ncandC, 1);
      continue;
    }

    if( 0==strcmp("-zlo", argv[i]) ) {
      cmd.zloP = TRUE;
      keep = i;
      i = getIntOpt(argc, argv, i, &cmd.zlo, 1);
      cmd.zloC = i-keep;
      checkIntLower("-zlo", &cmd.zlo, cmd.zloC, 2000000);
      checkIntHigher("-zlo", &cmd.zlo, cmd.zloC, -2000000);
      continue;
    }

    if( 0==strcmp("-zhi", argv[i]) ) {
      cmd.zhiP = TRUE;
      keep = i;
      i = getIntOpt(argc, argv, i, &cmd.zhi, 1);
      cmd.zhiC = i-keep;
      checkIntLower("-zhi", &cmd.zhi, cmd.zhiC, 2000000);
      checkIntHigher("-zhi", &cmd.zhi, cmd.zhiC, -2000000);
      continue;
    }

    if( 0==strcmp("-rlo", argv[i]) ) {
      cmd.rloP = TRUE;
      keep = i;
      i = getIntOpt(argc, argv, i, &cmd.rlo, 1);
      cmd.rloC = i-keep;
      checkIntHigher("-rlo", &cmd.rlo, cmd.rloC, 0);
      continue;
    }

    if( 0==strcmp("-rhi", argv[i]) ) {
      cmd.rhiP = TRUE;
      keep = i;
      i = getIntOpt(argc, argv, i, &cmd.rhi, 1);
      cmd.rhiC = i-keep;
      checkIntHigher("-rhi", &cmd.rhi, cmd.rhiC, 0);
      continue;
    }

    if( 0==strcmp("-lobin", argv[i]) ) {
      cmd.lobinP = TRUE;
      keep = i;
      i = getIntOpt(argc, argv, i, &cmd.lobin, 1);
      cmd.lobinC = i-keep;
      checkIntHigher("-lobin", &cmd.lobin, cmd.lobinC, 0);
      continue;
    }

    if( 0==strcmp("-zapfile", argv[i]) ) {
      cmd.zapfileP = TRUE;
      keep = i;
      i = getStringOpt(argc, argv, i, &cmd.zapfile, 1);
      cmd.zapfileC = i-keep;
      continue;
    }

    if( 0==strcmp("-baryv", argv[i]) ) {
      cmd.baryvP = TRUE;
      keep = i;
      i = getFloatOpt(argc, argv, i, &cmd.baryv, 1);
      cmd.baryvC = i-keep;
      checkFloatLower("-baryv", &cmd.baryv, cmd.baryvC, 0.1);
      checkFloatHigher("-baryv", &cmd.baryv, cmd.baryvC, -0.1);
      continue;
    }

    if( argv[i][0]=='-' ) {
      fprintf(stderr, "\n%s: unknown option `%s'\n\n",
              Program, argv[i]);
      usage();
    }
    argv[cmd.argc++] = argv[i];
  }/* for i */


  /*@-mustfree*/
  cmd.argv = argv+1;
  /*@=mustfree*/
  cmd.argc -= 1;

  if( 1>cmd.argc ) {
    fprintf(stderr, "%s: there should be at least 1 non-option argument(s)\n",
            Program);
    exit(EXIT_FAILURE);
  }
  if( 1<cmd.argc ) {
    fprintf(stderr, "%s: there should be at most 1 non-option argument(s)\n",
            Program);
    exit(EXIT_FAILURE);
  }
  /*@-compmempass*/  return &cmd;
}

